spring:
  server:
    port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 100MB
      content-type: text/html
file:
  path: D:/upload/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.etc.test.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl